(()=>{
const GREEN='#35d05b',BG='#0c0f12',PANEL='#13181d',LINE='#26313a',MUTED='#98a7b3';
const schools=[
{name:'University of Minnesota',state:'MN',region:'Midwest',size:'Large',setting:'Urban',division:'D1',majors:['Business','Biology','Psychology','Kinesiology','Nursing','Education','Engineering'],url:'https://gophersports.com/sports/softball'},
{name:'University of St. Thomas',state:'MN',region:'Midwest',size:'Medium',setting:'Urban',division:'D1',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education','Engineering'],url:'https://tommiesports.com/sports/softball'},
{name:'Minnesota State University Mankato',state:'MN',region:'Midwest',size:'Medium',setting:'College Town',division:'D2',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education','Engineering'],url:'https://msumavericks.com/sports/softball'},
{name:'University of Minnesota Duluth',state:'MN',region:'Midwest',size:'Medium',setting:'College Town',division:'D2',majors:['Business','Biology','Psychology','Exercise Science','Education','Engineering'],url:'https://umdbulldogs.com/sports/softball'},
{name:'Concordia University St. Paul',state:'MN',region:'Midwest',size:'Small',setting:'Urban',division:'D2',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education'],url:'https://cspbears.com/sports/softball'},
{name:'Winona State University',state:'MN',region:'Midwest',size:'Medium',setting:'College Town',division:'D2',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education'],url:'https://winonastatewarriors.com/sports/softball'},
{name:'Bemidji State University',state:'MN',region:'Midwest',size:'Small',setting:'College Town',division:'D2',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education'],url:'https://bsubeavers.com/sports/softball'},
{name:'St. Cloud State University',state:'MN',region:'Midwest',size:'Medium',setting:'College Town',division:'D2',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education'],url:'https://scsuhuskies.com/sports/softball'},
{name:'University of Iowa',state:'IA',region:'Midwest',size:'Large',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education','Engineering'],url:'https://hawkeyesports.com/sports/softball'},
{name:'Iowa State University',state:'IA',region:'Midwest',size:'Large',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Kinesiology','Education','Engineering'],url:'https://cyclones.com/sports/softball'},
{name:'University of Northern Iowa',state:'IA',region:'Midwest',size:'Medium',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education'],url:'https://unipanthers.com/sports/softball'},
{name:'Drake University',state:'IA',region:'Midwest',size:'Small',setting:'Urban',division:'D1',majors:['Business','Biology','Psychology','Health Sciences','Education','Engineering'],url:'https://godrakebulldogs.com/sports/softball'},
{name:'University of Wisconsin',state:'WI',region:'Midwest',size:'Large',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Kinesiology','Nursing','Education','Engineering'],url:'https://uwbadgers.com/sports/softball'},
{name:'University of Wisconsin Green Bay',state:'WI',region:'Midwest',size:'Medium',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education'],url:'https://greenbayphoenix.com/sports/softball'},
{name:'University of Wisconsin Eau Claire',state:'WI',region:'Midwest',size:'Medium',setting:'College Town',division:'D3',majors:['Business','Biology','Psychology','Kinesiology','Nursing','Education'],url:'https://blugolds.com/sports/softball'},
{name:'University of Wisconsin La Crosse',state:'WI',region:'Midwest',size:'Medium',setting:'College Town',division:'D3',majors:['Business','Biology','Psychology','Exercise Science','Education'],url:'https://uwlathletics.com/sports/softball'},
{name:'University of Nebraska',state:'NE',region:'Midwest',size:'Large',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Nutrition','Education','Engineering'],url:'https://huskers.com/sports/softball'},
{name:'South Dakota State University',state:'SD',region:'Midwest',size:'Medium',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education','Engineering'],url:'https://gojacks.com/sports/softball'},
{name:'University of South Dakota',state:'SD',region:'Midwest',size:'Medium',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Kinesiology','Nursing','Education'],url:'https://goyotes.com/sports/softball'},
{name:'North Dakota State University',state:'ND',region:'Midwest',size:'Medium',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Exercise Science','Nursing','Education','Engineering'],url:'https://gobison.com/sports/softball'},
{name:'University of North Dakota',state:'ND',region:'Midwest',size:'Medium',setting:'College Town',division:'D1',majors:['Business','Biology','Psychology','Kinesiology','Nursing','Education','Engineering'],url:'https://fightinghawks.com/sports/softball'}
];
const key='speed_pathway_guide_v1';
let data=JSON.parse(localStorage.getItem(key)||'{}');
const save=()=>localStorage.setItem(key,JSON.stringify(data));
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function yearPlan(y){const now=new Date().getFullYear(),yrs=y-now;if(yrs>=5)return {stage:'Explore',count:'5–10',text:'Learn what you like. Build skill and academic baselines. No mass emailing.',tasks:['Complete College Fit Builder','Explore 5 different types of colleges','Record verified baseline metrics','Set one academic and one athletic development goal']};if(yrs===4)return {stage:'Build',count:'10–15',text:'Start building college awareness and a broad preference list.',tasks:['Build a 10–15 school exploration list','Update verified testing','Learn NCAA/NAIA/JUCO differences','Save camps only at schools that genuinely fit']};if(yrs===3)return {stage:'Research',count:'20–30',text:'Build a broad, balanced list and begin organized research.',tasks:['Research 20–30 programs','Create Dream / Strong Fit / Explore groups','Update academics and video','Review recruiting communication rules for your class']};if(yrs===2)return {stage:'Engage',count:'20–30',text:'This is an active research and communication year. Keep the list balanced.',tasks:['Maintain 20–30 researched programs','Prioritize 10–15 strong-fit programs','Send appropriate program updates','Track questionnaires and camps','Meet with a Midwest Speed coach about list balance']};if(yrs===1)return {stage:'Narrow',count:'10–20',text:'Narrow based on genuine academic, lifestyle and softball fit.',tasks:['Narrow to 10–20 realistic programs','Follow up with priority programs','Compare academics, cost and roster opportunity','Track visits, camps and coach communication']};return {stage:'Decision',count:'5–10',text:'Focus on verified opportunities and the best total college fit.',tasks:['Compare final opportunities','Review admissions and financial deadlines','Confirm academic program fit','Make a decision based on the full college experience']}}
function score(s){let pts=0,max=0,why=[];const p=data.profile||{};function add(ok,w,label){max+=w;if(ok){pts+=w;why.push('✓ '+label)}}
add(!p.states?.length||p.states.includes(s.state),25,'Geography');add(!p.size||p.size==='Any'||p.size===s.size,15,'School size');add(!p.setting||p.setting==='Any'||p.setting===s.setting,10,'Campus setting');add(!p.divisions?.length||p.divisions.includes(s.division),15,'Division preference');add(!p.major||s.majors.some(m=>m.toLowerCase().includes(p.major.toLowerCase())||p.major.toLowerCase().includes(m.toLowerCase())),35,'Major/academic interest');return {n:Math.round(100*pts/max),why}}
function matches(){return schools.map(s=>({...s,...score(s)})).sort((a,b)=>b.n-a.n)}
function css(){const st=document.createElement('style');st.textContent=`#spGuide{position:fixed;inset:0;background:${BG};z-index:9999;color:#f4f7f9;overflow:auto;font-family:Inter,Segoe UI,Arial,sans-serif}.spWrap{max-width:1180px;margin:auto;padding:22px}.spHead{display:flex;justify-content:space-between;gap:14px;align-items:center;border-bottom:1px solid ${LINE};padding-bottom:16px}.spBrand{font-weight:900;font-size:22px}.spBrand b{color:${GREEN}}.spClose,.spBtn{border:0;border-radius:9px;padding:10px 13px;font-weight:800;cursor:pointer}.spClose{background:#202830;color:white}.spBtn{background:${GREEN};color:#071008}.spBtn.alt{background:#192127;color:white;border:1px solid #33404a}.spGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.spCard{background:${PANEL};border:1px solid ${LINE};border-radius:14px;padding:17px}.spK{font-size:11px;color:${MUTED};text-transform:uppercase;letter-spacing:.08em}.spV{font-size:26px;font-weight:900;margin-top:5px}.spTwo{display:grid;grid-template-columns:1fr 1fr;gap:14px}.spTask{padding:11px 0;border-bottom:1px solid ${LINE};display:flex;gap:9px}.spTask input{width:auto}.spSchool{padding:13px 0;border-bottom:1px solid ${LINE}}.spScore{color:${GREEN};font-weight:900}.spForm{display:grid;grid-template-columns:1fr 1fr;gap:10px}.spForm label{font-size:12px;color:${MUTED}}.spForm input,.spForm select{margin-top:5px;width:100%;background:#0e1418;color:white;border:1px solid ${LINE};border-radius:8px;padding:10px}.spTabs{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.spTabs button{background:#152019;color:white;border:1px solid ${LINE};padding:9px 12px;border-radius:9px;cursor:pointer}.spTabs button.on{border-color:${GREEN};color:${GREEN}}.spNotice{background:#182018;border:1px solid #31553a;border-radius:12px;padding:13px;color:#c9e8ce}.spWarn{background:#211d12;border:1px solid #5a4c25;border-radius:12px;padding:13px;color:#ead8a4}@media(max-width:800px){.spGrid,.spTwo,.spForm{grid-template-columns:1fr}.spWrap{padding:14px}}`;document.head.appendChild(st)}
function addEntry(){const nav=document.querySelector('.nav');if(nav&&!document.getElementById('spNav')){const b=document.createElement('button');b.id='spNav';b.innerHTML='★ My Pathway';b.onclick=open;nav.prepend(b)}const top=document.querySelector('.topbar');if(top&&!document.getElementById('spTop')){const b=document.createElement('button');b.id='spTop';b.className='action';b.textContent='My Pathway';b.onclick=open;top.appendChild(b)}}
function open(){if(document.getElementById('spGuide'))return;const el=document.createElement('div');el.id='spGuide';document.body.appendChild(el);render('home')}
function render(tab){const el=document.getElementById('spGuide'),p=data.profile||{},plan=yearPlan(+p.gradYear||2030),ms=matches(),done=data.done||{};el.innerHTML=`<div class="spWrap"><div class="spHead"><div><div class="spBrand"><b>SPEED</b> PATHWAY</div><div style="color:${MUTED};font-size:12px">Your college softball GPS</div></div><button class="spClose" onclick="document.getElementById('spGuide').remove()">Back to Speed</button></div><div class="spTabs"><button data-t="home" class="${tab==='home'?'on':''}">Today</button><button data-t="fit" class="${tab==='fit'?'on':''}">College Fit Builder</button><button data-t="schools" class="${tab==='schools'?'on':''}">My Matches</button><button data-t="list" class="${tab==='list'?'on':''}">My College List</button><button data-t="camps" class="${tab==='camps'?'on':''}">Camp Watch</button></div><div id="spBody"></div></div>`;el.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>render(b.dataset.t));const body=el.querySelector('#spBody');
if(tab==='home'){const top=ms[0];body.innerHTML=`<div class="spNotice"><b>${p.name?esc(p.name)+', your':'Your'} pathway is in the ${plan.stage} stage.</b><br>${plan.text}</div><div class="spGrid"><div class="spCard"><div class="spK">Graduation</div><div class="spV">${esc(p.gradYear||'Set year')}</div></div><div class="spCard"><div class="spK">Schools to explore</div><div class="spV">${plan.count}</div></div><div class="spCard"><div class="spK">Saved schools</div><div class="spV">${(data.saved||[]).length}</div></div><div class="spCard"><div class="spK">Top current fit</div><div class="spV" style="font-size:17px">${p.gradYear?esc(top.name):'Build profile'}</div></div></div><div class="spTwo"><div class="spCard"><h3>What should I do next?</h3>${plan.tasks.map((t,i)=>`<label class="spTask"><input type="checkbox" data-task="${i}" ${done[plan.stage+i]?'checked':''}><span><b>${esc(t)}</b><br><small style="color:${MUTED}">Recommended for a ${esc(p.gradYear||'future')} graduate</small></span></label>`).join('')}</div><div class="spCard"><h3>Your pathway</h3><p style="color:${MUTED}">Speed Pathway is built to guide decisions, not rank athletes. Your college list should reflect academics, lifestyle, geography and softball fit.</p><button class="spBtn" id="buildNow">Build / Update My Fit</button><div class="spWarn" style="margin-top:14px"><b>Important:</b> Athletic alignment is a coaching/development conversation. A match score is not an offer prediction.</div></div></div>`;body.querySelectorAll('[data-task]').forEach(c=>c.onchange=()=>{data.done=data.done||{};data.done[plan.stage+c.dataset.task]=c.checked;save()});body.querySelector('#buildNow').onclick=()=>render('fit')}
if(tab==='fit'){body.innerHTML=`<div class="spCard"><h2>Build My College Fit</h2><p style="color:${MUTED}">Tell us what you want from college. You can change this anytime as your priorities change.</p><div class="spForm"><label>Name<input id="pfName" value="${esc(p.name)}"></label><label>Graduation year<input id="pfYear" type="number" min="2026" max="2035" value="${esc(p.gradYear||2030)}"></label><label>Intended major / field<input id="pfMajor" placeholder="e.g. Nursing, Business, Biology" value="${esc(p.major)}"></label><label>Preferred school size<select id="pfSize"><option>Any</option>${['Small','Medium','Large'].map(x=>`<option ${p.size===x?'selected':''}>${x}</option>`)}</select></label><label>Campus setting<select id="pfSetting"><option>Any</option>${['Urban','College Town'].map(x=>`<option ${p.setting===x?'selected':''}>${x}</option>`)}</select></label><label>Preferred states (comma separated)<input id="pfStates" placeholder="MN, IA, WI" value="${esc((p.states||[]).join(', '))}"></label><label>Divisions to explore (comma separated)<input id="pfDiv" placeholder="D1, D2, D3" value="${esc((p.divisions||[]).join(', '))}"></label><label>Maximum distance from home<input id="pfDist" placeholder="e.g. 300 miles" value="${esc(p.distance)}"></label></div><button class="spBtn" id="saveFit" style="margin-top:14px">Save & Build My Matches</button></div>`;body.querySelector('#saveFit').onclick=()=>{data.profile={name:pfName.value.trim(),gradYear:+pfYear.value,major:pfMajor.value.trim(),size:pfSize.value,setting:pfSetting.value,states:pfStates.value.toUpperCase().split(',').map(x=>x.trim()).filter(Boolean),divisions:pfDiv.value.toUpperCase().split(',').map(x=>x.trim()).filter(Boolean),distance:pfDist.value.trim()};save();render('schools')}}
if(tab==='schools'){body.innerHTML=`<div class="spCard"><h2>My College Matches</h2><p style="color:${MUTED}">These are preference matches from the current Midwest starter catalog. They are research recommendations, not recruiting predictions.</p>${ms.slice(0,15).map((s,i)=>`<div class="spSchool"><div style="display:flex;justify-content:space-between;gap:10px"><div><b>${i+1}. ${esc(s.name)}</b><br><small style="color:${MUTED}">${s.state} • ${s.division} • ${s.size} • ${s.setting}</small></div><div class="spScore">${s.n}% FIT</div></div><div style="font-size:12px;margin-top:6px;color:#b8c3cc">${s.why.join(' &nbsp; ')||'Broaden your preferences to compare this school.'}</div><div style="margin-top:8px"><button class="spBtn alt" data-save="${esc(s.name)}">${(data.saved||[]).includes(s.name)?'Saved ✓':'Add to My List'}</button> <a href="${s.url}" target="_blank" rel="noopener" style="color:${GREEN};font-size:12px;margin-left:8px">Research softball program</a></div></div>`).join('')}</div>`;body.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{data.saved=data.saved||[];if(!data.saved.includes(b.dataset.save))data.saved.push(b.dataset.save);save();render('schools')})}
if(tab==='list'){const sv=data.saved||[];body.innerHTML=`<div class="spCard"><h2>My College List</h2><p style="color:${MUTED}">Your list should evolve as you learn more. The goal is a balanced list, not the longest list.</p>${sv.length?sv.map(n=>`<div class="spSchool"><b>${esc(n)}</b><button class="spBtn alt" data-rm="${esc(n)}" style="float:right;padding:6px 9px">Remove</button><br><small style="color:${MUTED}">Next: research academics, cost, campus life and softball fit.</small></div>`).join(''):'<div class="spWarn">No schools saved yet. Open My Matches and begin exploring.</div>'}</div>`;body.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{data.saved=sv.filter(x=>x!==b.dataset.rm);save();render('list')})}
if(tab==='camps'){const sv=data.saved||[];body.innerHTML=`<div class="spCard"><h2>Camp Watch</h2><p style="color:${MUTED}">Camp alerts should serve your pathway, not drive it. Save schools first; then track camps only for programs that fit your goals.</p>${sv.length?sv.map(n=>{const s=schools.find(x=>x.name===n);return `<div class="spSchool"><b>${esc(n)}</b><br><small style="color:${MUTED}">Watchlist active. Use the program link to verify current camp dates.</small>${s?`<br><a href="${s.url}" target="_blank" rel="noopener" style="color:${GREEN}">Open program site</a>`:''}</div>`}).join(''):'<div class="spWarn">Add schools to My College List to activate your Camp Watch list.</div>'}<div class="spNotice" style="margin-top:14px"><b>Next integration:</b> automatic camp-date monitoring and notifications can plug into this watchlist without changing the athlete workflow.</div></div>`}
}
css();const obs=new MutationObserver(addEntry);obs.observe(document.documentElement,{childList:true,subtree:true});addEntry();window.SpeedPathwayGuide={open};
})();